platform :ios, '8.0'
#use_frameworks!
#纯oc项目中 通过pod导入纯oc项目, 一般都不使用frameworks https://www.jianshu.com/p/ac629a1cb8f5
inhibit_all_warnings!
#【inhibit_all_warnings!】可以去掉pods警告,加入需要重新pod install才能生效
target ‘Waiting_iOS’ do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Aspects', '~> 1.4.1'
  pod 'NullSafe', '~> 1.2.2'
  pod 'SAMKeychain', '~> 1.5.3'
  pod 'Masonry', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '4.2.2'
  pod 'MJRefresh', '~> 3.1.15.6'
  pod 'RSKImageCropper', '~> 2.1.0'
  pod 'JPush'
  pod 'FSActionSheet', '~> 1.0.1'
  pod 'IQKeyboardManager', '~> 6.1.1'
  pod 'UMCCommon', '~> 1.5.2'
  pod 'UMCAnalytics', '~> 5.5.0'
  pod 'YYKit', '~> 1.0.9'
  pod 'SVProgressHUD'
  
  #TTGTagCollectionView 标签视图
  pod 'TTGTagCollectionView', '1.9.0'
  
  #日志框架
  pod 'CocoaLumberjack', '~> 3.2.1'

  # shareSDK
  # 主模块(必须)
  pod 'mob_sharesdk', '~> 4.1.4'
  # ShareSDKPlatforms模块其他平台，按需添加
  pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
  pod 'mob_sharesdk/ShareSDKPlatforms/GooglePlus'
  pod 'mob_sharesdk/ShareSDKPlatforms/Instagram'
  pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'

  #网易云信IM&音视频完整版
  #pod 'NIMSDK', '~> 5.6.0'
  #网易云信UI组件完整版本(包含NIMSDK)
  #依赖库 SDWebImage、Toast、M80AttributedLabel、TZImagePickerController 缺少会自动下载
  pod 'NIMKit/Full'
  
end
