platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!
#【inhibit_all_warnings!】可以去掉pods警告,加入需要重新pod install才能生效
target ‘Waiting_iOS’ do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Aspects', '~> 1.4.1'
  pod 'NullSafe', '~> 1.2.2'
  pod 'NJKWebViewProgress', '~> 0.2.3'
  pod 'SAMKeychain', '~> 1.5.3'
  pod 'Masonry', '~> 1.1.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage', '~> 4.4.2'
  pod 'MJRefresh', '~> 3.1.15.6'
  pod 'YBPopupMenu', '~> 1.1.2'
  pod 'WechatOpenSDK'
  pod 'RSKImageCropper', '~> 2.1.0'
  pod 'JPush'
  pod 'SobotKit', '~> 2.6.3'
  pod 'FSActionSheet', '~> 1.0.1'
  pod 'IQKeyboardManager', '~> 6.1.1'
  pod 'SDCycleScrollView', '~> 1.75'
  pod 'UMCCommon', '~> 1.5.2'
  pod 'UMCAnalytics', '~> 5.5.0'
  pod 'BMKLocationKit', '~> 1.2.1'
  pod 'YYKit', '~> 1.0.9'
  
  # shareSDK
  # 主模块(必须)
  pod 'mob_sharesdk', '~> 4.1.4'
  # ShareSDKPlatforms模块其他平台，按需添加
  pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
  pod 'mob_sharesdk/ShareSDKPlatforms/GooglePlus'
  pod 'mob_sharesdk/ShareSDKPlatforms/Instagram'
  pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'

end
